[[main]]
  name = "About"
  pageRef = "about/"
  weight = 10
  [main.params]
    alias = false

[[main]]
  name = "Projects"
  pageRef = "projects/"
  weight = 20
  [main.params]
    alias = false

[[main]]
  name = "Blog"
  pageRef = "blog/"
  weight = 30
  [main.params]
    alias = false
[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://www.linkedin.com/in/thomascross257contact/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/ThomasCross257"
  weight = 20