[[main]]
    name = "Home"
    pageRef = "/"
    weight = 10
    [main.params]
        alias = true

[[main]]
    name = "Projects"
    pageRef = "/projects/"
    weight = 20
    [main.params]
        alias = true

[[main]]
    name = "Blog"
    pageRef = "/blog/"
    weight = 30
    [main.params]
        alias = true

[[main]]
    name = "About"
    pageRef = "/about/"
    weight = 40
    [main.params]
        alias = true
[[main]]
    name = "GitHub"
    url = "https://github.com/ThomasCross257"
    weight = 50
    [main.params]
        alias = true