[[main]]
    name = "Home"
    pageRef = "/"
    weight = 10
    [main.params]
        alias = true

[[main]]
    name = "Projects"
    pageRef = "/projects/"
    weight = 20
    [main.params]
        alias = true

[[main]]
    name = "Blog"
    pageRef = "/blog/"
    weight = 30
    [main.params]
        alias = true

[[main]]
    name = "About"
    pageRef = "/about/"
    weight = 40
    [main.params]
        alias = true
[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/ThomasCross257"
  weight = 20