[style]
    primary = "#0082D4"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
[navigation]
    anchor = true
    logo = ""
    color = "body"
    fixed = true
    overlay = false
    overlayMode = "dark"
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"

[social]
    enabled = false

[home]
    # sections = ["projects", "blog"]
    fullCover = false
    centerHeadline = false
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "primary"
        width = 4
        align = "start"
[sections]
    [sections.blog]
        title = "Blog"
        sort = "date"
        reverse = true
        cols = 3
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom card-body-margin"
        homepage = 3
        separator = true
    [sections.projects]
        title = "Projects"
        sort = "date"
        reverse = true
        cols = 3
        background = "body-tertiary"
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom card-body-margin"
        homepage = 3
        separator = false

[favicon]
    logo = "img/PersonalLogoFavicon.png"
    sizes = [16, 32, 48, 64, 128, 256, 512]